### ISSUE TITLE
Manual labeling

### ISSUE THREAD

**Issue by joachimpoutaraud** [ear-team/bambird#1]
While testing the cool functions for segmenting sound units, I thought it could be nice to implement an additional function to ease the manual labeling of the sound units if we want to evaluate the clustering with [`cluster_eval`](https://github.com/ear-team/bambird/blob/master/bambird/cluster.py#L540).

Here is a code snippet that could maybe be useful for doing so. 

```python

import maad
import librosa
import bambird
import pandas as pd
import ipywidgets as widgets
import IPython.display as ipd
import matplotlib.pyplot as plt
from scipy.signal import butter, lfilter

class ManualLabeling:
    
    def __init__(self, df_cluster, params):

        self.df_cluster = df_cluster.copy()
        self.params = params['PARAMS_EXTRACT']
        self.manual_label = []        

        button1 = widgets.Button(description="Signal")
        button2 = widgets.Button(description="Noise")
        buttons = widgets.HBox(children=[button1, button2])
        button1.on_click(self.signal)
        button2.on_click(self.noise)

        self.all_widgets = widgets.HBox(children=[buttons, widgets.Output()])
        self.roi(0)
        
    def roi(self, i):
        filename   = self.df_cluster['fullfilename_ts'][i]
        tmin       = self.df_cluster['min_t'][i]
        tmax       = self.df_cluster['max_t'][i]
        fmin       = self.df_cluster['min_f'][i]
        fmax       = self.df_cluster['max_f'][i]
        sr         = self.params["SAMPLE_RATE"]
        duration   = self.params["AUDIO_DURATION"]
        n_fft      = self.params["NFFT"]
        
        print(f'Loading region of interest (ROI): {i}/{len(self.df_cluster)}')
        
        # Load and filter the segmented signal
        sig, sr = librosa.load(filename, sr=sr)
        b, a = butter(5, [fmin, fmax], fs=sr, btype='band')       
        sig = lfilter(b, a, sig)

        # Compute spectrogram
        Sxx, tn, fn, ext = maad.sound.spectrogram(sig, sr,nperseg=n_fft, noverlap=n_fft // 2)
        X = maad.util.power2dB(Sxx, db_range=96) + 96
        
        ipd.clear_output(wait=False)
        
        # Display spectrogram
        fig, ax = plt.subplots(figsize=(4,2))
        maad.util.plot_spectrogram(X, log_scale=False, colorbar=False, ax=ax, now=False, extent=ext)
        ax.yaxis.set_label_position("right")
        ax.set_ylim([fmin, fmax])
        ax.yaxis.tick_right()
        plt.show()
        
        # Display audio unit and widgets
        ipd.display(ipd.Audio(sig, rate=sr))
        ipd.display(self.all_widgets)

    def signal(self, b):
        self.manual_label.append(1.0)
        ipd.clear_output(wait=False)
        
        if len(self.manual_label) == len(self.df_cluster):
            self.df_cluster['manual_label'] = self.manual_label
            ipd.display(self.df_cluster)
        else:
            i = len(self.manual_label)
            self.roi(i)

    def noise(self, b):
        self.manual_label.append(0.0)
        ipd.clear_output(wait=False)
        
        if len(self.manual_label) == len(self.df_cluster):
            self.df_cluster['manual_label'] = self.manual_label
            ipd.display(self.df_cluster)
            
        else:
            i = len(self.manual_label)
            self.roi(i)
```

Creating an object of the class `ManualLabeling(df_cluster, params)` will then make it possible to iterate over all the units found in the `df_cluster` and allow the user to click either on the `Signal` or `Noise` buttons to append the values in the `manual_labels` list.

![unit](https://user-images.githubusercontent.com/63192177/208980088-8624f8aa-af64-4be6-bcb6-b6013ceb18a8.png)

**Comment by shaupert** [comment]
Thanks a lot for the suggestion and the code. I'll try it and see how to add it into the bambird package.
Best
Sylvain

**Comment by ear-team** [comment]
Joachim, you are now a contributor of Bambird such that you can add this new features in the code.
I would suggest to let the user using this function as soon as they get a collection of ROIs not only after getting the clusters (for instance by changing df_cluster by df_rois).  In the same way, in order to be compliant with Bambird, it would be useful to save the manual labelling in a csv file (with at least 2 columns : "filename_ts" and "manual_label")  that could be loaded in the function cluster_eval. Thanks a lot.

**Comment by joachimpoutaraud** [comment]
I have tested the new implementation of a `label_rois` function that I will add to the `cluster.py` file. This outputs a dataframe with the labeled acoustic units and also allow the possibility to output a csv file with all the columns of the `df_cluster` + an additional column for the `manual_label`.

However, I just tried to push the modification but I do not have write access to the repository. Is it possible to allow it or should we work differently?

**Comment by shaupert** [comment]
Yes, I know the problem. You can't push directly on the master branch for "safety" reason, but you can push your change on production branch. My practice is to work and make changes on production and then, every time we think that it worth it and that we check that there is no obvious bug, we merge production into master (pull request). So in you case, you should pull the production branch and work on it. Sorry, I forgot to mention that.
